name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - 'release/**'
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build, Test and push to docker hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{values.java_version}}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{values.java_version}}'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker Image
        run: |
          docker build -t ${{values.org_owner}}/${{values.artifact_id}}:latest .

      - name: Push Docker Image
        run: |
          docker push ${{values.org_owner}}/${{values.artifact_id}}:latest
