apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: templates
  annotations:
    github.com/project-slug: alokkulkarni/templates
spec:
  type: other
  lifecycle: unknown
  owner: guests
