apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: shell-script-template
  title: Add shellscript as a scaffolder action to any template
  description: Add shell script to an existing project
  tags:
    - recommended
    - shell-script
spec:
  owner: ak
  system: ak-idp
  type: service

  steps:
  - id: hello-world
    name: Hello World
    action: shell:execute
    input:
      script: |
        echo "Hello, World!"
        echo "Current directory: $(pwd)"
        echo "Current user: $(whoami)"

  output:
    links:
      - title: shell-script-output
        url: ${{ steps.hello-world.output.stdout }}
