kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{values.artifact_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.artifact_id}}
  template:
    metadata:
      labels:
        app: ${{values.artifact_id}}
        app.kubernetes.io/component: backstage
        backstage.io/kubernetes-id: ${{values.artifact_id}}
    spec:
      containers:
        - name: ${{values.artifact_id}}
          image: ${{values.org_owner}}/${{values.artifact_id}}:latest
          ports:
            - name: http-8585
              containerPort: 8585
              protocol: TCP
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
