kind: Service
apiVersion: v1
metadata:
  name: ${{values.artifact_id}}
  labels:
    app: ${{values.artifact_id}}
    app.kubernetes.io/component: backstage
    backstage.io/kubernetes-id: ${{values.artifact_id}}}
spec:
  ports:
    - name: http-8585
      port: 8585
      protocol: TCP
      targetPort: 8585
  selector:
    app: ${{values.artifact_id}}
  type: NodePort
