name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAGS: latest ${{ github.sha }}
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE }}
  USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

        - name: unit tests
          run: mvn -B test --file pom.xml

        - name: build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml
        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.REGISTRY_NAMESPACE }}/${{env.IMAGE_NAME}}:${{IMAGE_TAGS}}

        - name: login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ env.USERNAME }}
            password: ${{ env.PASSWORD }}

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.REGISTRY_NAMESPACE }}/${{env.IMAGE_NAME}}:${{IMAGE_TAGS}}
