apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: ${{values.artifact_id}}
    backstage.io/code-coverage: enabled #scm-only
    jenkins.io/job-full-name: 'folder-name/project-name,folder-name/project-name'
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: ${{values.destination.owner + "/" + values.destination.repo}}
  providesApis:
    - ${{values.artifact_id}} 